---
- hosts: docker-swarm-ci
  become: false

  tasks:
#  - name: login to registry
#    command: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 878919740555.dkr.ecr.us-east-1.amazonaws.com
#    ignore_errors: yes

  - name: create docker image using war file
    command: docker build -t todoapp .
    args:
      chdir: /home/ec2-user/docker/todoapp

  - name: verify that the image was created correctly.
    command: docker images --filter reference=todoapp

  - name: create tag to image
    command: docker tag todoapp:latest registry.dev-ops.work/todoapp:latest

  - name: push image on to dockerhub
    command: docker push registry.dev-ops.work/todoapp:latest

  - name: remove docker images form ansible server
    command: docker rmi todoapp:latest registry.dev-ops.work/todoapp:latest
    ignore_errors: yes
