---
- hosts: swarm-node-master
  become: false
  tasks:

#  - name: login to registry
#    command: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 878919740555.dkr.ecr.us-east-1.amazonaws.com
#    ignore_errors: yes

  - name: Remove if we have old docker stack
    command: docker stack rm todoapp
    ignore_errors: yes

  - name: Remove current docker image
    command: docker rmi -f 878919740555.dkr.ecr.us-east-1.amazonaws.com/todoapp:latest
    ignore_errors: yes
    register: result
    failed_when:
      - result.rc == 0
      - '"docker" not in result.stdout'
  
  - name: pull from registry
    command: docker pull 878919740555.dkr.ecr.us-east-1.amazonaws.com/todoapp:latest
    ignore_errors: yes

  - name: Deploying docker stack
    command: chdir=/home/ec2-user/docker/todoapp docker stack deploy --compose-file docker-compose.yml todoapp

